service: scrapper-imoveis
frameworkVersion: '3'

plugins:
  # - '@hewmen/serverless-plugin-typescript'  
  # - serverless-jetpack
  - serverless-offline


package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1 # or whatever your region is
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  vpc:
    securityGroupIds:
      - sg-0261a572de2d0458d
    subnetIds:
      - subnet-0ce68677dd0405115  

functions:
  api:
    handler: dist/main.handler
    timeout: 120 # Tempo maximo de 2 minutos para a execução da função
    events:
      - http:
          path: /
          method: ANY
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer  # Este é o ID do Autorizador criado no API Gateway
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer  # Este é o ID do Autorizador criado no API Gateway

  callerFindImoveis:
    handler: dist/main.callFindProperties
    timeout: 120 # Tempo maximo de 2 minutos para a execução da função
    events:
      - schedule: cron(50 6 ? * TUE,THU,SAT *)
          
custom:
  serverless-offline:
    httpPort: 3000

# custom:
#   # Enable warmup on all functions (only for production and staging)
#   warmup:      
#       - production
#       - staging